export const DEFAULT_SIGKILL_DELAY_MS = 5_000;
export const DEFAULT_HEARTBEAT_INTERVAL_MS = 5_000;
export const DEFAULT_HEARTBEAT_QUIET_THRESHOLD_MS = 10_000;
export const DEFAULT_CONTEXT_LOCK_WAIT_MS = 30_000;
export const DEFAULT_CONTEXT_STALE_LOCK_MS = 300_000;
export const DEFAULT_DEPENDENCY_WAIT_MS = 600_000;
export const DEFAULT_BRANCH_SWITCH_TIMEOUT_MS = 15_000;
export const DEFAULT_COMMAND_TIMEOUT_MS = 120_000;
export const DEFAULT_FAILURE_CONTEXT_CHARS = 2_000;
export const DEFAULT_REPAIR_REPORT_CHARS = 4_000;
export const DEFAULT_REPAIR_TRANSCRIPT_CHARS = 6_000;
export const DEFAULT_RETRY_PROBABILITY = 0.15;
export const DEFAULT_REMEDIATION_RATE = 0.25;
export const DEFAULT_URL_MAX_LENGTH = 2_048;
export const DEFAULT_SHORT_CODE_MIN_LENGTH = 7;

