import { createHash } from "node:crypto";
import { type BundleSignature, verifyChainHeadSignature } from "./signing.ts";

/**
 * Three separate claims live in a bundle signature, and the old check answered one of them.
 *
 *   1. The bundle is internally consistent: the chain rehashes and the signature over the head
 *      verifies. This is what a self-contained bundle can prove on its own.
 *   2. The bundle was made by someone in particular. It cannot prove this on its own, because
 *      the public key travels inside the bundle it signs: anyone can edit the bundle, rehash
 *      it, sign it with a key of their own, ship that key in the manifest, and the signature
 *      verifies against it.
 *   3. The machine that produced it was not compromised. Nothing here establishes that, and a
 *      valid signature must never be read as if it did.
 *
 * So authenticity needs an identity from outside the bundle, and that is what a trust policy
 * is: fingerprints the verifier was told to expect, by someone other than the bundle.
 */
export type SignerVerdict = "trusted" | "untrusted" | "invalid" | "unverified";

export interface TrustPolicy {
  /**
   * `any-key` checks consistency only and can never return trusted; it is the honest name for
   * verifying a bundle whose signer nobody named. `expected-signers` is the authenticity check.
   */
  readonly mode: "any-key" | "expected-signers";
  /** Fingerprints, as `sha256:<hex>` over the SPKI DER. */
  readonly signers?: readonly string[] | undefined;
}

export interface SignerJudgement {
  readonly signer: SignerVerdict;
  readonly fingerprint: string;
  readonly reason: string;
}

/** Stable identity for a key: SHA-256 over the SPKI DER bytes the manifest carries. */
export function keyFingerprint(publicKeySpkiBase64: string): string {
  const digest = createHash("sha256").update(Buffer.from(publicKeySpkiBase64, "base64")).digest();
  return `sha256:${digest.toString("hex")}`;
}

export function judgeSigner(
  chainHead: string,
  signature: BundleSignature,
  policy: TrustPolicy,
): SignerJudgement {
  const fingerprint = keyFingerprint(signature.publicKey);

  if (!verifyChainHeadSignature(chainHead, signature)) {
    return {
      signer: "invalid",
      fingerprint,
      reason:
        "the signature does not verify against the chain head, so the bundle is not even " +
        "internally consistent. That is a different finding from an unrecognized signer",
    };
  }

  // A key the run generated for itself vouches for the run that made it. It establishes that
  // the bundle has not changed since it was written and nothing at all about who wrote it.
  if (signature.keySource === "ephemeral") {
    return {
      signer: "untrusted",
      fingerprint,
      reason:
        "the bundle was signed with an ephemeral key, generated by the run it vouches for. " +
        "It shows the bundle is unchanged since it was written and says nothing about who " +
        "wrote it",
    };
  }

  if (policy.mode === "any-key") {
    return {
      signer: "untrusted",
      fingerprint,
      reason:
        `the signature verifies against the key shipped in the bundle (${fingerprint}), but no ` +
        "expected signer was named, so this shows the bundle is internally consistent and not " +
        "who made it. Name an expected signer to check authenticity",
    };
  }

  const expected = policy.signers ?? [];
  if (expected.length === 0) {
    return {
      signer: "unverified",
      fingerprint,
      reason: "the trust policy names no signers, so there was nothing to check the key against",
    };
  }

  if (!expected.includes(fingerprint)) {
    return {
      signer: "untrusted",
      fingerprint,
      reason:
        `the bundle was signed by ${fingerprint}, which the trust policy does not name. ` +
        `Expected one of: ${expected.join(", ")}`,
    };
  }

  return {
    signer: "trusted",
    fingerprint,
    reason: `the bundle was signed by ${fingerprint}, which the trust policy names`,
  };
}
